[project]
name = "forsym"
version = "0.1.0"  # 
description = "Description of your project"
dependencies = [
  "anytree",
  "hatchling",
  "lxml",
  "pyyaml",
  "tyro",
  "numpy>2,<3",
]  # Add dependencies if there are any

[project.optional-dependencies]
mujoco-warp = [
  "mjviser>=0.0.14",
  "mujoco-warp",
]
teleoperation = [
  "mjviser>=0.0.14",
  "mink>=1.2,<2",
  "robot-descriptions>=3.1,<4",
]
all = ["forsym[mujoco-warp,teleoperation]"]

[project.scripts]
forsym-view-forest = "forsym.visualisation.mujoco_warp_viewer:main"
forsym-teleop-franka = "forsym.visualisation.mink_franka_viewer:main"
forsym-generate-trees = "forsym.lsystems2.assemblers.pipeline_runner:main"

[build-system] # this is to fix issue with pixi pip install on editable mode
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 120

[tool.ty.environment]
python = "./.pixi/envs/default/bin/python"
