[project]
name = "forsym"
version = "0.1.0"
description = "Generate fruit-bearing URDF trees for simulation based 99% on 'Gentle Manipulation of Tree Branches: A Contact-Aware Policy Learning Approach' by Jacob et al. (2025)"
requires-python = ">=3.10"
dependencies = [
  "anytree",
  "pyyaml",
  "numpy>=2,<3",
  "tyro",
  "usd-core",
  "urdf-usd-converter",
]

[project.optional-dependencies]
mujoco = [
  "mujoco>=3",
]
mujoco-warp = [
  "mjviser>=0.0.14",
  "mujoco>=3,<4",
  "mujoco-warp",
]
teleoperation = [
  "mjviser>=0.0.14",
  "mink>=1.2,<2",
  "mujoco>=3,<4",
  "robot-descriptions>=3.1,<4",
]
all = ["forsym[mujoco-warp,teleoperation]"]

[project.scripts]
# forsym-view-forest = "forsym.visualisation.mujoco_warp_viewer:main"
# forsym-teleop-franka = "forsym.visualisation.mink_franka_viewer:main"
forsym-generate-trees = "forsym.generation:main"
forsym-generate-mjcf = "forsym.generation:main_mujoco"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 120

[tool.ty.environment]
python = "./.pixi/envs/default/bin/python"
